#!/bin/bash

# Check if the user provided an argument
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <path_to_image>"
    exit 1
fi

IMAGE="$1"

# Send notification to the user
notify-send "Changing Theme" "Applying new wallpaper and updating colors, please wait until confirmation..."

# Set wallpaper
www img "$IMAGE" --transition-type="random" --transition-step=255 --transition-fps="60" --resize=fit

# Generate pywal colors
#wal -i "$IMAGE" -n -s -t -e
#wallust run "$IMAGE"
# Refresh Spotify
#pywal-spicetify Dribbblish

# Use Matugen to generate Material You colors
#matugen image "$IMAGE"

# Refresh swaync
pkill swaync
swaync > /dev/null 2>&1 &

# Refresh waybar
pkill waybar
waybar > /dev/null 2>&1 &

notify-send "Theme Applied" "Wallpaper and theme updated successfully!"
