#!/bin/bash

# Check if argument (playlist link) is given
if [ -z "$1" ]; then
    echo "Usage: $0 <playlist_url>"
    exit 1
fi

URL="$1"

# Download playlist in 1080p, save in playlist folder with numbering
yt-dlp -f "bv*[height<=1080]+ba/best[height<=1080]" \
    -o "%(playlist_title)s/%(playlist_index)03d - %(title)s.%(ext)s" \
    "$URL"

